





CREATE TABLE TCURSO
(  COD_CURSO INTEGER NOT NULL PRIMARY KEY,
   NOME VARCHAR2(30),
   VALOR NUMBER(8,2),
   CARGA_HORARIA INTEGER
);

SELECT * FROM TCURSO;


INSERT INTO TCURSO VALUES(1,'ORACLE SQL e PL/SQL',500,25);
INSERT INTO TCURSO VALUES(2,'ORACLE DBA',499,25);
INSERT INTO TCURSO VALUES(3,'JAVA FUNDAMENTOS E OO',1500,100);
INSERT INTO TCURSO VALUES(4,'JAVASERVER FACES',1600,100);
