



-- Sequence
CREATE SEQUENCE SEQ_ALUNO START WITH 4;

-- selecTsequence
SELECT SEQ_ALUNO.NEXTVAL FROM DUAL;

INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (SEQ_ALUNO.NEXTVAL,'VALDO','CANOAS','11000000');

INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (SEQ_ALUNO.NEXTVAL,'ANDRE','IVOTI','12000000');

SELECT * FROM TALUNO;


--Valor atual da sequence
SELECT SEQ_ALUNO.CURRVAL FROM DUAL;