



UPDATE TCONTRATO SET
  DESCONTO = NULL
WHERE COD_CONTRATO = 4;

UPDATE TCONTRATO SET
  DESCONTO = NULL
WHERE COD_CONTRATO = 3;

SELECT Count(*) AS QTDE_REGISTROS
FROM TCONTRATO;

SELECT * FROM TCONTRATO

--COUNT -> IGNORA NULOS
SELECT Count(DESCONTO)
FROM TCONTRATO;

SELECT * FROM TALUNO

--Qtde de registros com estado informado
SELECT  Count(ESTADO)  FROM   TALUNO;

--QTDE DE estados diferentes
SELECT Count(DISTINCT(ESTADO)) FROM TALUNO;



--QUANT DE REGISTROS POR estado
SELECT Estado, Count(*)
FROM TALUNO
GROUP BY Estado;

--
SELECT Sum(DESCONTO),
       Avg(DESCONTO),
       Count(DESCONTO),
       Round(Avg( Nvl(DESCONTO,0) ), 2)
FROM TCONTRATO;

SELECT * FROM TCONTRATO