


--TOTAL DE CONTRATO POR ESTADO E DATA
-- 2 atributos p GROUP  BY
SELECT ALU.Estado, Trunc(CON.DATA) AS DATA,
       SUM(CON.Total) TOTAL, Count(*) qtde
FROM   TALUNO ALU, TCONTRATO CON
WHERE  ALU.COD_ALUNO = CON.COD_ALUNO
GROUP  BY  ALU.Estado, Trunc(CON.DATA)
ORDER  BY  ALU.ESTADO, DATA DESC;




--TOTAL DE CONTRATO POR ESTADO
SELECT ALU.Estado,
       SUM(CON.Total) TOTAL, Count(*) qtde
FROM   TALUNO ALU, TCONTRATO CON
WHERE  ALU.COD_ALUNO = CON.COD_ALUNO
GROUP  BY  ALU.Estado
ORDER  BY  ALU.ESTADO


--Having - filtrar coluna com funcao de grupo
SELECT COD_ALUNO, AVG(TOTAL) MEDIA
FROM TCONTRATO
WHERE COD_ALUNO > 0
HAVING AVG(Total) > 500
GROUP BY COD_ALUNO
ORDER BY COD_ALUNO