
 --ALTERAR REGISTRO DA TABELA
 UPDATE TCONTRATO SET
   DESCONTO = 18
 WHERE COD_CONTRATO = 2;


 UPDATE TCONTRATO SET
   DESCONTO = 20         ,
   DATA = '05/06/2013'   ,
   TOTAL = 750
 WHERE COD_CONTRATO = 2;