

  CREATE TABLE TDESCONTO
  ( CLASSE VARCHAR(1) PRIMARY KEY,
    INFERIOR NUMBER(4,2),
    SUPERIOR NUMBER(4,2)
   );

  INSERT INTO TDESCONTO VALUES ('A',00,10);
  INSERT INTO TDESCONTO VALUES ('B',11,15);
  INSERT INTO TDESCONTO VALUES ('C',16,20);
  INSERT INTO TDESCONTO VALUES ('D',21,25);
  INSERT INTO TDESCONTO VALUES ('E',26,30);

  SELECT * FROM TDESCONTO;


  COMMIT;


  ---------

  SELECT * FROM TCONTRATO

  UPDATE TCONTRATO SET
  DESCONTO = 27
  WHERE COD_CONTRATO = 6;


  UPDATE TCONTRATO SET
  DESCONTO = 18
  WHERE COD_CONTRATO = 5;


  -------------
  SELECT	CON.COD_CONTRATO AS CONTRATO, CON.DESCONTO,
          DES.CLASSE AS DESCONTO
  FROM	  TCONTRATO CON, TDESCONTO DES
  WHERE CON.DESCONTO BETWEEN DES.INFERIOR AND DES.SUPERIOR
  ORDER BY CON.COD_CONTRATO;


  --Mostrar cursos vendidos
  SELECT CUR.COD_CURSO, CUR.NOME, ITE.VALOR
  FROM TCURSO CUR, TITEM ITE
  WHERE CUR.COD_CURSO = ITE.COD_CURSO


  --Mostrar cursos nao vendidos
  SELECT CUR.COD_CURSO, CUR.NOME, ITE.COD_ITEM
  FROM TCURSO CUR, TITEM ITE
  WHERE CUR.COD_CURSO = ITE.COD_CURSO(+)
  AND ITE.COD_ITEM IS NULL;

  SELECT * FROM TCURSO

  INSERT INTO TCURSO VALUES (6, 'PHP', 1000, 100);
  INSERT INTO TCURSO VALUES (7,'LOGICA',100,20)



  --Add coluna na tabela
  ALTER TABLE TCURSO ADD PRE_REQ INTEGER;


  SELECT * FROM TCURSO

  UPDATE TCURSO SET PRE_REQ = 7
      WHERE COD_CURSO = 1;

  UPDATE TCURSO SET PRE_REQ = 7
      WHERE COD_CURSO = 3;

  UPDATE TCURSO SET PRE_REQ = 1
      WHERE COD_CURSO = 2;

  UPDATE TCURSO SET PRE_REQ = 3
      WHERE COD_CURSO = 4;

  UPDATE TCURSO SET PRE_REQ = 7
      WHERE COD_CURSO = 6;